title: General Lee
author:
  name: David Lee Parker
  # email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Lee's world wide website of wonderful works.

remote_theme: https://github.com/jekyll/minima
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-feed
minima:
  skin: dark
