title: General Lee
author:
  name: David Lee Parker
  # email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Welcome to my website. This is where I write about my various projects and post other random tidbits of useful stuff. My goal is for this site to be like a message board and a what-not shelf combined into one.

remote_theme: https://github.com/jekyll/minima
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
minima:
  skin: dark
